name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - "backend/**"
      - "postman/**"
      - ".github/workflows/**"
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend server
        working-directory: backend
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 3

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Postman API tests with CSV
        run: |
          newman run postman/simple-backend.postman_collection.json \
            -d login_full_test.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: reports/report.html

      - name: Upload backend log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-log
          path: backend/server.log

  # deploy:
  #   needs: backend-tests
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: self-hosted
  #   environment: 
  #     name: Production
  #     url: http://13.212.186.166:3000

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Execute Server Script
  #       # GỌI FILE SCRIPT TRÊN SERVER VÀ TRUYỀN THAM SỐ
  #       # github.workspace: Là đường dẫn thư mục code mà Runner vừa tải về
  #       run: |
  #         ~/my-deploy-script.sh "${{ github.sha }}" "${{ github.workspace }}"